# Generated by Django 3.0.7 on 2020-07-26 21:26

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('Image', models.ImageField(null=True, upload_to='images/')),
                ('Full_name', models.CharField(max_length=100, null=True)),
                ('Date_of_Birth', models.DateField(null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True)),
                ('Marital_Status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], max_length=2, null=True)),
                ('Home_Address', models.TextField(null=True)),
                ('Mobile_Number', models.CharField(max_length=10, null=True)),
                ('region', models.CharField(choices=[('GR', 'Greater Accra'), ('ER', 'Eastern'), ('CR', 'Central'), ('WR', 'Western'), ('AR', 'Ashanti'), ('VR', 'Volta'), ('OT', 'Oti'), ('NR', 'Northern'), ('SR', 'Savannah'), ('NE', 'North East'), ('UE', 'Upper East'), ('UW', 'Upper West'), ('WN', 'Western North'), ('BA', 'Brong Ahafo'), ('BE', 'Bono East'), ('AF', 'Ahafo')], max_length=2, null=True)),
                ('Dues_Payment', models.CharField(choices=[('Paid', 'Paid'), ('UnPaid', 'Unpaid')], max_length=6, null=True)),
                ('member_id', models.CharField(default=main.models.id_no, max_length=10, primary_key=True, serialize=False)),
                ('Shop_Name', models.TextField(null=True)),
                ('RGD_Registered', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('Business_Registration_No', models.CharField(max_length=20, null=True)),
                ('Operation_Location', models.CharField(max_length=100, null=True)),
                ('Principal_Activity', models.CharField(max_length=200, null=True)),
                ('Business_Details', models.TextField(null=True)),
                ('Operation_Mode', models.CharField(choices=[('Importer', 'Importer'), ('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler')], max_length=15, null=True)),
                ('Date_registered', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('Date_registered',),
            },
        ),
    ]
