# Generated by Django 3.0.7 on 2020-07-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Tin_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Business_Details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Business_Registration_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Home_Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='members',
            name='Mobile_Number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Operation_Location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Principal_Activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Shop_Name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
