# Generated by Django 3.0.7 on 2020-09-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200909_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Date_of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Marital_Status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Operation_Mode',
            field=models.CharField(blank=True, choices=[('Importer', 'Importer'), ('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='region',
            field=models.CharField(blank=True, choices=[('GR', 'Greater Accra'), ('ER', 'Eastern'), ('CR', 'Central'), ('WR', 'Western'), ('AR', 'Ashanti'), ('VR', 'Volta'), ('OT', 'Oti'), ('NR', 'Northern'), ('SR', 'Savannah'), ('NE', 'North East'), ('UE', 'Upper East'), ('UW', 'Upper West'), ('WN', 'Western North'), ('BA', 'Brong Ahafo'), ('BE', 'Bono East'), ('AF', 'Ahafo')], max_length=2, null=True),
        ),
    ]
