# Generated by Django 3.0.7 on 2020-09-15 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200915_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
