# Generated by Django 3.0.7 on 2020-09-15 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_members_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
