# Generated by Django 3.0.7 on 2020-09-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200915_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Operation_Mode',
            field=models.CharField(blank=True, choices=[('Importer', 'Importer'), ('ImportRtl', 'Importer & Retailer'), ('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler')], max_length=15, null=True),
        ),
    ]
